[target.riscv64gc-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tmemory.x", # memory.x must appear BEFORE link.x
  "-C", "link-arg=-Tlink.x",
]
    runner = "qemu-system-riscv64 -M virt -nographic --kernel"

[build]
target = "riscv64gc-unknown-none-elf"
